# Generated by Django 2.2.19 on 2021-02-28 06:37

import django.db.models.deletion
import django.utils.timezone
import finance.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "cash_flow",
                    models.CharField(
                        choices=[("revenue", "Receita"), ("expense", "Despesa")],
                        default="expense",
                        max_length=15,
                        verbose_name="Fluxo",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "description",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "description",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "buy_order",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ordem de Compra"
                    ),
                ),
                (
                    "requester",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Solicitante"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "due_date",
                    models.DateField(null=True, verbose_name="Data de Vencimento"),
                ),
                (
                    "transacted_at",
                    models.DateField(null=True, verbose_name="Data da Transação"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="Anotações"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=finance.models.get_upload_to,
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "bill",
                    models.FileField(
                        blank=True,
                        upload_to=finance.models.get_upload_to,
                        verbose_name="Boleto",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pago?")),
                (
                    "is_recurrent",
                    models.BooleanField(default=False, verbose_name="Recorrente?"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.Category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.CostCenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-transacted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                ("issued_at", models.DateField(verbose_name="Data de Emissão")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Imposto",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("invoice", "Nota Fiscal"),
                            ("debit", "Nota de Débito"),
                            ("loan", "Empréstimo"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=finance.models.get_upload_to,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(default=False, verbose_name="Já recebido?"),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="finance.CostCenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="finance.ServiceOrder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebível",
                "verbose_name_plural": "Recebíveis",
                "ordering": ["-issued_at", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["due_date", "id"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.transaction",),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[],
            options={
                "verbose_name": "Conta Paga",
                "verbose_name_plural": "Contas Pagas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.transaction",),
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.transaction",),
        ),
    ]
