# Generated by Django 2.2.16 on 2021-02-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_auto_20210220_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_received",
            field=models.BooleanField(default=False, verbose_name="Já recebido?"),
        ),
    ]
