# Generated by Django 2.2.16 on 2021-02-23 04:34

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_invoice_is_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="category",
            field=models.CharField(
                choices=[
                    ("invoice", "Nota Fiscal"),
                    ("debit", "Nota de Débito"),
                    ("loan", "Empréstimo"),
                ],
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="document",
            field=models.FileField(
                blank=True,
                upload_to=finance.models.get_upload_to,
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="document",
            field=models.FileField(
                blank=True,
                upload_to=finance.models.get_upload_to,
                verbose_name="Comprovante",
            ),
        ),
    ]
