version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=genesis
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment: &environment
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DJANGO_SETTINGS_MODULE=core.development
      - SECRET_KEY=${SECRET_KEY}
      - JUPYTER_CONFIG_DIR=/code/jupyter/config/
    depends_on: &depends_on
      - db

  jupyter:
    build:
      context: .
      dockerfile: dockerfile.dev
    command: bash -c "jupyter notebook"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    environment:
      *environment
    depends_on:
      *depends_on


volumes:
  mysql-db:
