version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=genesis
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    stdin_open: true # @TODO remover antes de deploy
    tty: true # @TODO remover antes de deploy
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
    depends_on:
      - db

volumes:
  mysql-db:
