# Generated by Django 2.2.16 on 2020-11-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcompany",
            options={
                "ordering": ("project", "company"),
                "verbose_name": "Distribuidor do Projeto",
                "verbose_name_plural": "Distribuidores do Projeto",
            },
        ),
    ]
