# Generated by Django 2.2.19 on 2022-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcompany",
            options={
                "ordering": ("-project", "company__company_name"),
                "verbose_name": "distribuidor no projeto",
                "verbose_name_plural": "distribuidores no projeto",
            },
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="cutoff",
            field=models.DateField(
                help_text="Data de mensuração do estoque",
                null=True,
                verbose_name="Data Base",
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="deadline",
            field=models.DateField(
                help_text="Prazo para envio dos documentos",
                null=True,
                verbose_name="Prazo para Envio",
            ),
        ),
    ]
