# Generated by Django 2.2.16 on 2020-11-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201109_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcompany',
            options={'ordering': ('project', 'company'), 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
