# Generated by Django 2.2.19 on 2022-11-14 05:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0004_auto_20220827_1707"),
        ("projects", "0002_auto_20220827_1709"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCompanyDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("projeto", "Projeto")],
                        default="projeto",
                        max_length=255,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.models.UploadTo("projects/"),
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento do projeto",
                "verbose_name_plural": "documentos do projeto",
            },
        ),
    ]
