# Generated by Django 2.2.16 on 2020-11-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20201109_0312"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("circularizacao", "Circularização de Estoque"),
                    ("inventario", "Inventário Físico"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=200,
                verbose_name="Tipo de projeto",
            ),
            preserve_default=False,
        ),
    ]
