# Generated by Django 2.2.16 on 2020-11-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project", unique_together={("date", "category")},
        ),
        migrations.RemoveField(model_name="project", name="description",),
    ]
