# Generated by Django 2.2.16 on 2020-11-13 02:06

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20201112_0307"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcompany",
            name="justification_received",
            field=models.BooleanField(
                default=False, verbose_name="Justificativas recebidas"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="justification_received_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="justification_received"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="justification_sent",
            field=models.BooleanField(
                default=False, verbose_name="Justificativas enviadas"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="justification_sent_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="justification_sent"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="justification_validated",
            field=models.BooleanField(
                default=False, verbose_name="Justificativas validadas"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="justification_validated_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="justification_validated"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="letter_sent",
            field=models.BooleanField(default=False, verbose_name="Envio da carta"),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="letter_sent_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="letter_sent"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="manipulated",
            field=models.BooleanField(default=False, verbose_name="Modelo consolidado"),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="manipulated_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="manipulated"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="report_request",
            field=models.BooleanField(
                default=False, verbose_name="Solicitação de relatórios"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="report_request_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="report_request"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="report_response",
            field=models.BooleanField(
                default=False, verbose_name="Recebimento dos relatórios"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="report_response_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="report_response"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="retter_received",
            field=models.BooleanField(
                default=False, verbose_name="Recebimento da carta"
            ),
        ),
        migrations.AddField(
            model_name="projectcompany",
            name="retter_received_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="retter_received"
            ),
        ),
    ]
