# Generated by Django 2.2.16 on 2020-11-13 02:09

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_auto_20201113_0206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcompany",
            name="report_request_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="report_request",
                verbose_name="Solicitação de relatórios em",
            ),
        ),
    ]
