# Generated by Django 2.2.16 on 2020-11-13 02:11

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_auto_20201113_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcompany",
            name="justification_received_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="justification_received",
                verbose_name="Justificativas recebidas em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="justification_sent_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="justification_sent",
                verbose_name="Justificativas enviadas em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="justification_validated_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="justification_validated",
                verbose_name="Justificativas validadas em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="letter_sent_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="letter_sent",
                verbose_name="Envio da carta em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="manipulated_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="manipulated",
                verbose_name="Modelo consolidado em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="report_response_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="report_response",
                verbose_name="Recebimento dos relatórios em",
            ),
        ),
        migrations.AlterField(
            model_name="projectcompany",
            name="retter_received_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="retter_received",
                verbose_name="Recebimento da carta em",
            ),
        ),
    ]
