# Generated by Django 2.2.16 on 2020-11-07 15:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "code_sap",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Código SAP"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(max_length=100, verbose_name="Razão Social"),
                ),
                (
                    "fantasy_name",
                    models.CharField(max_length=100, verbose_name="Nome Fantasia"),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Syagri", "Syagri"),
                            ("Agrotis", "Agrotis"),
                            ("SAP", "SAP"),
                            ("Totvs", "Totvs"),
                            ("Outros", "Outros"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="ERP",
                    ),
                ),
                (
                    "retroactive",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Retroativo"
                    ),
                ),
                (
                    "designated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Designado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuidor",
                "verbose_name_plural": "Distribuidores",
                "ordering": ["trade_name"],
            },
        ),
        migrations.CreateModel(
            name="Focal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Anotações"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Cargo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
                "ordering": ["status", "name"],
            },
        ),
        migrations.CreateModel(
            name="Rtv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Anotações"),
                ),
            ],
            options={
                "verbose_name": "Rtv",
                "verbose_name_plural": "Rtvs",
                "ordering": ["status", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyRtv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                    ),
                ),
                (
                    "rtv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comercial.Rtv"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyFocal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                    ),
                ),
                (
                    "focal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Focal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="focal",
            field=models.ManyToManyField(
                blank=True,
                related_name="company",
                through="comercial.CompanyFocal",
                to="comercial.Focal",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="rtv",
            field=models.ManyToManyField(
                blank=True,
                related_name="company",
                through="comercial.CompanyRtv",
                to="comercial.Rtv",
            ),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=254, verbose_name="Endereço"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(default="", max_length=2, verbose_name="Estado"),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="CEP"
                    ),
                ),
                (
                    "ibge",
                    models.CharField(blank=True, max_length=9, verbose_name="IBGE"),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Código"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Apelido"
                    ),
                ),
                ("document", models.CharField(max_length=14, verbose_name="CNPJ")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Contato"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "inventory",
                    models.BooleanField(default=True, verbose_name="Controla Estoque"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiais",
                "ordering": ["status", "company__name", "city", "nickname"],
                "unique_together": {("document", "code", "nickname", "company")},
            },
        ),
    ]
