# Generated by Django 2.2.16 on 2020-12-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="system",
            field=models.CharField(
                choices=[
                    ("Syagri", "Syagri"),
                    ("Agrotis", "Agrotis"),
                    ("SAP", "SAP"),
                    ("Totvs", "Totvs"),
                    ("Outros", "Outros"),
                    ("Não conhecido", "Não conhecido"),
                ],
                default="Não conhecido",
                max_length=40,
                verbose_name="ERP",
            ),
        ),
    ]
