# Generated by Django 2.2.16 on 2020-10-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="fantasy", new_name="fantasy_name",
        ),
    ]
