# Generated by Django 2.2.19 on 2022-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_auto_20210728_0132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="system",
            field=models.CharField(
                choices=[
                    ("siagri", "Siagri"),
                    ("agrotis", "Agrotis"),
                    ("sap", "SAP"),
                    ("totvs", "Totvs"),
                    ("other", "Outros"),
                    ("unknown", "Não conhecido"),
                ],
                default="unknown",
                max_length=40,
                verbose_name="ERP",
            ),
        ),
    ]
