# Generated by Django 2.2.16 on 2020-10-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0004_auto_20201007_0230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=254, verbose_name="Endereço"
            ),
        ),
    ]
