# Generated by Django 2.2.16 on 2020-11-09 02:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnixProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "description",
                    models.CharField(
                        help_text="Normalmente segue o padrão: Nome do Produto - Tamanho da Embalagem Tipo de Unidade.",
                        max_length=200,
                        verbose_name="Descrição completa",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Apenas o nome, sem complementos. Exemplo: Cruiser, Cruiser Opti, Zapp QI, Zapp Pro.",
                        max_length=150,
                        verbose_name="Nome do produto",
                    ),
                ),
                (
                    "unit_size",
                    models.CharField(
                        help_text='Tamanho da unidade vendida. Se for vendido em caixa, utilize " 1 ".',
                        max_length=4,
                        verbose_name="Tamanho da embalagem",
                    ),
                ),
                (
                    "unit_mesure",
                    models.CharField(
                        choices=[
                            ("KG", "Kilos"),
                            ("G", "Gramas"),
                            ("L", "Litros"),
                            ("ML", "Mililitros"),
                            ("CX", "Caixa"),
                        ],
                        help_text="Unidade em que o produto é vendido ou medido no estoque",
                        max_length=2,
                        verbose_name="Tipo de unidade",
                    ),
                ),
                (
                    "unit_volume",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Fator de multiplicação da unidade vendida. Difere da embalagem em casos de caixas, frascos, pacotes, etc",
                        max_digits=7,
                        verbose_name="Volume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onix",
                "verbose_name_plural": "Onix",
                "ordering": ["prefix", "unit_volume"],
                "unique_together": {
                    ("prefix", "unit_size", "unit_mesure", "unit_volume")
                },
            },
        ),
        migrations.CreateModel(
            name="SyngentaProduct",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "agicode",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Agicode",
                    ),
                ),
                ("family", models.CharField(max_length=150, verbose_name="Família")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição completa"),
                ),
                (
                    "onix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syngenta",
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syngenta",
                "verbose_name_plural": "Syngenta",
                "ordering": ["description"],
                "unique_together": {("onix", "agicode")},
            },
        ),
        migrations.CreateModel(
            name="CompanyProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código utilizado pelo distribuidor para identificar o produto nos relatórios.",
                        max_length=20,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Código utilizado pelo distribuidor para identificar o produto nos relatórios.",
                        max_length=80,
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "onix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuidor",
                "verbose_name_plural": "Distribuidor",
                "ordering": ["created_at"],
                "unique_together": {("onix", "company", "code", "description")},
            },
        ),
    ]
