# Generated by Django 2.2.19 on 2021-07-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20201108_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyproduct",
            name="code",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Código utilizado pelo distribuidor para identificar o produto nos relatórios.",
                ),
                max_length=20,
                null=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="companyproduct",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Descrição utilizado pelo distribuidor para identificar o produto nos relatórios.",
                max_length=80,
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="onixproduct",
            name="unit_mesure",
            field=models.CharField(
                choices=[
                    ("KG", "Kilos"),
                    ("G", "Gramas"),
                    ("L", "Litros"),
                    ("ML", "Mililitros"),
                    ("CX", "Caixa"),
                ],
                help_text="Unidade em que o produto é medido no estoque ou vendido.",
                max_length=2,
                verbose_name="Tipo de unidade",
            ),
        ),
    ]
