# Generated by Django 2.2.16 on 2020-11-07 15:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CutDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "date",
                    models.DateField(
                        help_text="Data de mensuração do estoque",
                        verbose_name="Data Base",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Nome do projeto ou descrição do momento em que se mensura os estoques",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Base",
                "verbose_name_plural": "Datas Base",
                "ordering": ("date",),
                "unique_together": {("date", "description")},
            },
        ),
        migrations.CreateModel(
            name="SyngentaBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque informado pela Syngenta. (Posição Sales Force)",
                        max_digits=9,
                        null=True,
                        verbose_name="Saldo Syngenta",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.CutDate",
                        verbose_name="Data Base",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo Syngenta",
                "verbose_name_plural": "Saldos Syngenta",
                "ordering": ("date", "company", "product"),
                "unique_together": {("date", "company", "product", "balance")},
            },
        ),
        migrations.CreateModel(
            name="Justification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                ("description", models.TextField(verbose_name="Justificativa")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.CutDate",
                        verbose_name="Data Base",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificativa",
                "verbose_name_plural": "Justificativas",
                "ordering": ("date", "company", "product"),
                "unique_together": {("date", "company", "product")},
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "owned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico",
                        max_digits=9,
                        null=True,
                        verbose_name="EF",
                    ),
                ),
                (
                    "sold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de venda para entrega futura faturada com CFOP 5922, 6922",
                        max_digits=9,
                        null=True,
                        verbose_name="VEF",
                    ),
                ),
                (
                    "sent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico do distribuidor armazenado em poder de terceiros (Remessa para enviada)",
                        max_digits=9,
                        null=True,
                        verbose_name="Em Terceiros",
                    ),
                ),
                (
                    "received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico de terceiros armazenado em poder do distribuidor (Remessa recebida)",
                        max_digits=9,
                        null=True,
                        verbose_name="De Terceiros",
                    ),
                ),
                (
                    "transit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico em trânsito",
                        max_digits=9,
                        null=True,
                        verbose_name="Em Trânsito",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque calculado. Saldo = EF - VEF + Em Terceiros - De Terceiros +- Transito",
                        max_digits=9,
                        null=True,
                        verbose_name="Saldo Calculado",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.CutDate",
                        verbose_name="Data Base",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item",
                        to="comercial.Store",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
                "ordering": ("date", "company", "product", "store"),
            },
        ),
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "owned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico",
                        max_digits=9,
                        null=True,
                        verbose_name="EF",
                    ),
                ),
                (
                    "sold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de venda para entrega futura faturada com CFOP 5922, 6922",
                        max_digits=9,
                        null=True,
                        verbose_name="VEF",
                    ),
                ),
                (
                    "sent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico do distribuidor armazenado em poder de terceiros (Remessa para enviada)",
                        max_digits=9,
                        null=True,
                        verbose_name="Em Terceiros",
                    ),
                ),
                (
                    "received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico de terceiros armazenado em poder do distribuidor (Remessa recebida)",
                        max_digits=9,
                        null=True,
                        verbose_name="De Terceiros",
                    ),
                ),
                (
                    "transit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque físico em trânsito",
                        max_digits=9,
                        null=True,
                        verbose_name="Em Trânsito",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Saldo de estoque calculado. Saldo = EF - VEF + Em Terceiros - De Terceiros +- Transito",
                        max_digits=9,
                        null=True,
                        verbose_name="Saldo Calculado",
                    ),
                ),
                (
                    "adjust",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="Divergência",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.CutDate",
                        verbose_name="Data Base",
                    ),
                ),
                (
                    "justification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index",
                        to="stock.Justification",
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.OnixProduct",
                        verbose_name="Produto Onix",
                    ),
                ),
                (
                    "syngenta_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index",
                        to="stock.SyngentaBalance",
                        verbose_name="Saldo Syngenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidado",
                "verbose_name_plural": "Consolidados",
                "ordering": ("date", "company", "product"),
                "unique_together": {("date", "company", "product")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("import", "Modelo de Importação"),
                            ("justification", "Modelo de Justificativas"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("file", models.FileField(upload_to="stock/", verbose_name="Arquivo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="comercial.Company",
                        verbose_name="Distribuidor",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="stock.CutDate",
                        verbose_name="Data Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ("date", "company", "category"),
                "unique_together": {("date", "company", "category")},
            },
        ),
    ]
