# Generated by Django 2.2.16 on 2020-10-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20201008_0044"),
        ("comercial", "0006_auto_20201015_0259"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cutdate",
            options={
                "ordering": ("date",),
                "verbose_name": "Data Base",
                "verbose_name_plural": "Datas Base",
            },
        ),
        migrations.AlterModelOptions(
            name="index",
            options={
                "ordering": ("date", "company", "product"),
                "verbose_name": "Consolidado",
                "verbose_name_plural": "Consolidados",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("date", "company", "product", "store"),
                "verbose_name": "Item Base",
                "verbose_name_plural": "Itens Base",
            },
        ),
        migrations.AlterModelOptions(
            name="justification",
            options={
                "ordering": ("date", "company", "product"),
                "verbose_name": "Justificativa",
                "verbose_name_plural": "Justificativas",
            },
        ),
        migrations.AlterModelOptions(
            name="syngentabalance",
            options={
                "ordering": ("date", "company", "product"),
                "verbose_name": "Saldo Syngenta",
                "verbose_name_plural": "Saldos Syngenta",
            },
        ),
        migrations.AddField(
            model_name="syngentabalance",
            name="balance",
            field=models.DecimalField(
                decimal_places=3,
                default=9,
                help_text="Saldo de estoque informado pela Syngenta. (Posição Sales Force)",
                max_digits=9,
                verbose_name="Saldo Syngenta",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cutdate", unique_together={("date", "description")},
        ),
        migrations.AlterUniqueTogether(
            name="index", unique_together={("date", "company", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="justification", unique_together={("date", "company", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="syngentabalance", unique_together={("date", "company", "product")},
        ),
    ]
