# Generated by Django 2.2.16 on 2020-10-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_auto_20201015_0343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="justification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="index",
                to="stock.Justification",
                verbose_name="Justificativa",
            ),
        ),
    ]
