# Generated by Django 2.2.16 on 2020-10-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20201015_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='justification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index', to='stock.Justification', verbose_name='Justificativa'),
        ),
    ]
