# Generated by Django 2.2.16 on 2020-10-16 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_auto_20201015_0259'),
        ('stock', '0005_auto_20201015_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.CharField(choices=[('import', 'Modelo de Importação'), ('justification', 'Modelo de Justificativas')], max_length=100, verbose_name='Tipo de Documento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='comercial.Company', verbose_name='Distribuidor')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='stock.CutDate', verbose_name='Data Base')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
