# Generated by Django 2.2.16 on 2020-10-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_auto_20201016_0310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Saldo de estoque calculado. Saldo = EF - VEF + Em Terceiros - De Terceiros +- Transito",
                max_digits=9,
                null=True,
                verbose_name="Saldo Calculado",
            ),
        ),
        migrations.AlterField(
            model_name="index",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.Company",
                verbose_name="Distribuidor",
            ),
        ),
        migrations.AlterField(
            model_name="index",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.CutDate",
                verbose_name="Data Base",
            ),
        ),
        migrations.AlterField(
            model_name="index",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.OnixProduct",
                verbose_name="Produto Onix",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.Company",
                verbose_name="Distribuidor",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.CutDate",
                verbose_name="Data Base",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.OnixProduct",
                verbose_name="Produto Onix",
            ),
        ),
        migrations.AlterField(
            model_name="justification",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.Company",
                verbose_name="Distribuidor",
            ),
        ),
        migrations.AlterField(
            model_name="justification",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.CutDate",
                verbose_name="Data Base",
            ),
        ),
        migrations.AlterField(
            model_name="justification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.OnixProduct",
                verbose_name="Produto Onix",
            ),
        ),
        migrations.AlterField(
            model_name="syngentabalance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.Company",
                verbose_name="Distribuidor",
            ),
        ),
        migrations.AlterField(
            model_name="syngentabalance",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.CutDate",
                verbose_name="Data Base",
            ),
        ),
        migrations.AlterField(
            model_name="syngentabalance",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.OnixProduct",
                verbose_name="Produto Onix",
            ),
        ),
    ]
