# Generated by Django 2.2.16 on 2020-09-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('code_sap', models.CharField(max_length=8, unique=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('system', models.CharField(choices=[('Syagri', 'Syagri'), ('Agrotis', 'Agrotis'), ('SAP', 'SAP'), ('Totvs', 'Totvs'), ('Outros', 'Outros')], max_length=40, verbose_name='ERP')),
                ('retroactive', models.BooleanField(default=False, verbose_name='Relatorio Retroativo')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Focal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('phone2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rtv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('phone2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rtv',
                'verbose_name_plural': 'Rtvs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Endereço')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='', max_length=2, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('code_ibge', models.CharField(blank=True, max_length=9, verbose_name='Código IBGE')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido')),
                ('document', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('inventory', models.BooleanField(default=True, verbose_name='Controla Estoque')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='syncomercial.Company')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['company__company_name', 'city', 'nickname'],
                'unique_together': {('document', 'code', 'nickname', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRtv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Company')),
                ('rtv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Rtv')),
            ],
            options={
                'verbose_name': 'Rtv do Distribuidor',
                'verbose_name_plural': 'Rtvs do Distribuidores',
                'ordering': ['company__company_name', 'rtv__name'],
                'unique_together': {('company', 'rtv')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Company')),
                ('focal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Focal')),
            ],
            options={
                'verbose_name': 'Responsável pelo Distribuidor',
                'verbose_name_plural': 'Responsável pelo Distribuidor',
                'ordering': ['company__company_name', 'focal__name'],
                'unique_together': {('company', 'focal')},
            },
        ),
    ]
