# Generated by Django 2.2.16 on 2020-09-07 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncomercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='retroactive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Relatorio Retroativo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system',
            field=models.CharField(blank=True, choices=[('Syagri', 'Syagri'), ('Agrotis', 'Agrotis'), ('SAP', 'SAP'), ('Totvs', 'Totvs'), ('Outros', 'Outros')], max_length=40, null=True, verbose_name='ERP'),
        ),
        migrations.AlterField(
            model_name='focal',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
