# Generated by Django 2.2.16 on 2020-09-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncomercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focal',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='rtv',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Rtv', 'verbose_name_plural': 'Rtvs'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['status', 'company__name', 'city', 'nickname'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='designated',
        ),
        migrations.AlterField(
            model_name='company',
            name='focal',
            field=models.ManyToManyField(blank=True, related_name='focal', to='syncomercial.Focal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rtv',
            field=models.ManyToManyField(blank=True, related_name='rtv', to='syncomercial.Rtv'),
        ),
    ]
