# Generated by Django 2.2.16 on 2020-09-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncomercial', '0002_auto_20200907_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='syncomercial.Company', verbose_name='Distribuidor'),
        ),
    ]
