# Generated by Django 2.2.16 on 2020-09-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncomercial', '0002_auto_20200928_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='code_ibge',
        ),
        migrations.AddField(
            model_name='store',
            name='ibge',
            field=models.CharField(blank=True, max_length=9, verbose_name='IBGE'),
        ),
        migrations.AlterField(
            model_name='company',
            name='designated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Designado'),
        ),
    ]
