# Generated by Django 2.2.19 on 2022-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Documento", "verbose_name_plural": "Documentos"},
        ),
    ]
